import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createVoiceSession, spokenAnswer} from '../src/nativeVoice.ts';
const answer={id:'answer-1',role:'assistant',status:'complete',content:'visible answer',created_at:'2026-10-09',metadata:{context:{}}};
const structured={...answer,content:'HIDDEN MODEL OUTPUT',metadata:{context:{satzantwort:{version:1,saetze:[{text:'Termin möglicherweise am Freitag.',belege:[1],verlaesslichkeit:'duenn',hinweis:'Nicht bestätigt.'}],hinweise:['Nicht alle Quellen ausgewertet.'],belege:[],akte:[{text:'HIDDEN QUOTE'}],verworfen:1,verworfen_pruefmodell:2}}}};
function fixture(){let n=0,active=true;const commands=[],drafts=[],states=[];const voice=createVoiceSession({post:body=>{commands.push(body);return true;},newId:()=>`00000000-0000-4000-8000-${String(++n).padStart(12,'0')}`,active:()=>active,changed:state=>states.push(state)});voice.probe();voice.event({id:commands.at(-1).id,state:'ready',text:'',dictationAvailable:true,speechAvailable:true});return {voice,commands,drafts,states,hide:()=>{active=false;},accept:text=>drafts.push(text)};}
const callback=(id,state,text='')=>({id,state,text,dictationAvailable:true,speechAvailable:true});
test('spoken answer keeps displayed uncertainty and coverage, never hidden model content',()=>{assert.equal(spokenAnswer(structured),'Termin möglicherweise am Freitag. (Nicht bestätigt.)\nNicht alle Quellen ausgewertet.\n2 Sätze verworfen (Prüfmodell).\nEin Satz verworfen, weil die Belege ihn nicht getragen haben.');assert.equal(spokenAnswer(answer),'visible answer\nOhne Beleg: Diese Antwort stützt sich auf keine Quelle aus deinem Gedächtnis.');assert.equal(spokenAnswer({...answer,role:'user'}),'');assert.equal(spokenAnswer({...answer,status:'error'}),'');assert.equal(spokenAnswer({...answer,content:'x'.repeat(8001)}),'');});
test('partials stay separate; final result appends to the original unsent draft',()=>{const f=fixture();f.voice.startDraft('Vorhanden',f.accept);const id=f.commands.at(-1).id;f.voice.event(callback(id,'listening','neu'));assert.deepEqual(f.drafts,[]);assert.equal(f.states.at(-1).partial,'neu');f.voice.finish();assert.equal(f.commands.at(-1).aktion,'spracheEnde');f.voice.event(callback(id,'completed','Neuer Text'));assert.deepEqual(f.drafts,['Vorhanden Neuer Text']);assert.equal(f.commands.some(c=>c.aktion.includes('Send')),false);});
test('cancel, old ids and malformed callbacks cannot overwrite the draft',()=>{const f=fixture();f.voice.startDraft('alt',f.accept);const old=f.commands.at(-1).id;f.voice.cancel();f.voice.event(callback(old,'completed','verworfen'));assert.deepEqual(f.drafts,[]);f.voice.startDraft('neu',f.accept);const current=f.commands.at(-1).id;f.voice.event(callback(old,'completed','falsche Sitzung'));f.voice.event({...callback(current,'completed','untrusted'),dictationAvailable:'yes'});f.voice.event(callback(current,'completed','x'.repeat(4001)));assert.deepEqual(f.drafts,[]);f.voice.event(callback(current,'completed','ok'));assert.deepEqual(f.drafts,['neu ok']);});
test('hidden/disposed sessions ignore late results and stop capture',()=>{const f=fixture();f.voice.startDraft('',f.accept);const id=f.commands.at(-1).id;f.hide();f.voice.event(callback(id,'completed','late'));assert.deepEqual(f.drafts,[]);f.voice.dispose();assert.equal(f.commands.at(-1).aktion,'spracheAbbrechen');const count=f.commands.length;f.voice.probe();f.voice.startDraft('a',f.accept);assert.equal(f.commands.length,count);});
test('changed source metadata blocks reading even with identical visible wording',async()=>{const f=fixture();await f.voice.read(answer,async()=>({...answer,metadata:{context:{source_links:[{episode_id:'new',label:'changed'}]}}}),()=>answer);assert.equal(f.commands.some(c=>c.aktion==='spracheVorlesen'),false);assert.equal(f.states.at(-1).phase,'idle');assert.match(f.states.at(-1).notice,/geändert/);});
test('explicit reading sends only the fresh visible answer and stops on cancel',async()=>{const f=fixture();await f.voice.read(structured,async()=>structured,()=>structured);const body=f.commands.at(-1);assert.equal(body.aktion,'spracheVorlesen');assert.match(body.text,/Nicht alle Quellen/);assert.doesNotMatch(body.text,/HIDDEN/);f.voice.cancel();assert.equal(f.commands.at(-1).aktion,'spracheStopp');});
test('late fetch cannot play a canceled, hidden, replaced or deleted answer',async()=>{for(const outcome of ['cancel','hide','replace','missing']){const f=fixture();let resolve;let current=answer;const reading=f.voice.read(answer,()=>new Promise(r=>{resolve=r;}),()=>current);if(outcome==='cancel')f.voice.cancel();if(outcome==='hide')f.hide();if(outcome==='replace')current={...answer,content:'new'};resolve(outcome==='missing'?undefined:answer);await reading;assert.equal(f.commands.some(c=>c.aktion==='spracheVorlesen'),false,outcome);}});
test('without local capability nothing records or plays',async()=>{const commands=[];const voice=createVoiceSession({post:b=>{commands.push(b);return false;},newId:()=>crypto.randomUUID(),active:()=>true,changed:()=>{}});voice.startDraft('keep',()=>assert.fail('no draft'));await voice.read(answer,async()=>answer,()=>answer);assert.equal(commands.length,0);});
test('network failure cannot start playback',async()=>{const f=fixture();await f.voice.read(answer,async()=>{throw Error('offline');},()=>answer);assert.equal(f.commands.some(c=>c.aktion==='spracheVorlesen'),false);assert.match(f.states.at(-1).notice,/prüfen/);});
test('denied local permission updates capability so the microphone does not keep offering a dead action',()=>{const f=fixture();f.voice.startDraft('keep',f.accept);const id=f.commands.at(-1).id;f.voice.event({...callback(id,'unavailable'),dictationAvailable:false});assert.equal(f.states.at(-1).dictationAvailable,false);const count=f.commands.length;f.voice.startDraft('keep',f.accept);assert.equal(f.commands.length,count);assert.deepEqual(f.drafts,[]);});
test('older native WebKit can generate a valid session id without randomUUID',async()=>{const native=await import('../src/nativeVoice.ts');assert.equal(typeof native.voiceRequestId,'function');const environment={crypto:{getRandomValues:array=>{array.fill(0);return array;}}};assert.equal(native.voiceRequestId(environment),'00000000-0000-4000-8000-000000000000');});
