import assert from 'node:assert/strict';
import {after,test} from 'node:test';
import {fileURLToPath} from 'node:url';
import {createServer} from 'vite';
const server=await createServer({root:fileURLToPath(new URL('..',import.meta.url)),plugins:[{name:'voice-hook-driver',enforce:'pre',resolveId(id){if(id==='virtual:voice-hooks')return '\0'+id;},load(id){if(id==='\0virtual:voice-hooks')return `export const useState=(...a)=>globalThis.__voiceDriver.state(...a);export const useRef=(...a)=>globalThis.__voiceDriver.ref(...a);export const useEffect=(...a)=>globalThis.__voiceDriver.effect(...a);`;},transform(code,id){if(id.endsWith('/src/ConversationVoice.tsx'))return code.replace("from 'react'","from 'virtual:voice-hooks'");}}],server:{middlewareMode:true,watch:null,ws:false,hmr:false},appType:'custom'});
after(()=>server.close());
const {useConversationVoice}=await server.ssrLoadModule('/src/ConversationVoice.tsx');
const {api}=await server.ssrLoadModule('/src/api.ts');
const answer={id:'a',role:'assistant',status:'complete',content:'Synthetic',created_at:'2026-10-09',metadata:{context:{}}};
const payload=id=>({conversation:{id},messages:[answer]});
function driver(){const states=[],refs=[],effects=[],pending=[];let s=0,r=0,e=0;const d={state(value){const i=s++;if(!(i in states))states[i]=value;return [states[i],next=>states[i]=typeof next==='function'?next(states[i]):next];},ref(value){return refs[r++]??={current:value};},effect(fn,deps){const i=e++;if(!effects[i]||deps.some((v,j)=>v!==effects[i].deps[j])){effects[i]?.cleanup?.();effects[i]={deps};pending.push(()=>effects[i].cleanup=fn());}},render(id,data,disabled=false){s=r=e=0;globalThis.__voiceDriver=d;return useConversationVoice(id,data,disabled);},effects(){pending.splice(0).forEach(fn=>fn());},close(){effects.forEach(x=>x.cleanup?.());}};return d;}
function environment(){const before={window:globalThis.window,document:globalThis.document};const win=new EventTarget(),doc=new EventTarget(),requests=[];win.crypto=globalThis.crypto;win.webkit={messageHandlers:{kingfisher:{postMessage:body=>requests.push(body)}}};doc.visibilityState='visible';doc.hasFocus=()=>true;globalThis.window=win;globalThis.document=doc;return {requests,win,doc,event(id,state,text=''){win.dispatchEvent(new CustomEvent('kingfisher:voice',{detail:{id,state,text,dictationAvailable:true,speechAvailable:true}}));},restore(){globalThis.window=before.window;globalThis.document=before.document;}};}
test('a conversation change probes capability after its own data arrives, not from the previous conversation',()=>{const env=environment(),d=driver();try{d.render('one',payload('one'));d.effects();const n=env.requests.length;d.render('two',payload('one'));d.effects();assert.equal(env.requests.length,n);d.render('two',payload('two'));d.effects();assert.equal(env.requests.at(-1).aktion,'spracheStatus');assert.equal(env.requests.length,n+1);}finally{d.close();env.restore();}});
test('hiding or busy transition cancels actual hook session and rejects its late dictation callback',()=>{for(const action of ['hidden','busy','unmount']){const env=environment(),d=driver();try{let voice=d.render('one',payload('one'));d.effects();env.event(env.requests.at(-1).id,'ready');voice=d.render('one',payload('one'));const drafts=[];voice.startDraft('keep',text=>drafts.push(text));const id=env.requests.at(-1).id;if(action==='hidden'){env.doc.visibilityState='hidden';env.doc.dispatchEvent(new Event('visibilitychange'));}if(action==='busy'){d.render('one',payload('one'),true);d.effects();}if(action==='unmount')d.close();assert.equal(env.requests.at(-1).aktion,'spracheAbbrechen');env.event(id,'completed','late');assert.deepEqual(drafts,[],action);}finally{d.close();env.restore();}}});
test('a late answer refresh after navigation is aborted and cannot speak into another conversation',async()=>{const env=environment(),d=driver(),old=api.getConversation;let resolve,signal;api.getConversation=(_id,s)=>{signal=s;return new Promise(r=>resolve=r);};try{let voice=d.render('one',payload('one'));d.effects();env.event(env.requests.at(-1).id,'ready');voice=d.render('one',payload('one'));voice.read(answer);assert.ok(signal);d.render('two',payload('one'));d.effects();assert.equal(signal.aborted,true);resolve(payload('one'));await new Promise(setImmediate);assert.equal(env.requests.some(x=>x.aktion==='spracheVorlesen'),false);}finally{api.getConversation=old;d.close();env.restore();}});
test('an old browser without bridge and randomUUID mounts and removes listeners without exception or GET',()=>{const env=environment(),d=driver();delete env.win.webkit;env.win.crypto={};const prior=Object.getOwnPropertyDescriptor(globalThis,'crypto');Object.defineProperty(globalThis,'crypto',{value:{},configurable:true});try{assert.doesNotThrow(()=>{d.render('one',payload('one'));d.effects();});assert.deepEqual(env.requests,[]);assert.doesNotThrow(()=>d.close());}finally{d.close();env.restore();Object.defineProperty(globalThis,'crypto',prior);}});
