import assert from 'node:assert/strict';
import {after,test} from 'node:test';
import {fileURLToPath} from 'node:url';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createServer} from 'vite';
const server=await createServer({root:fileURLToPath(new URL('..',import.meta.url)),server:{middlewareMode:true,watch:null,ws:false,hmr:false},appType:'custom'});
after(()=>server.close());
const {VoiceDraftControls,VoiceDraftStatus,VoiceReply}=await server.ssrLoadModule('/src/ConversationVoice.tsx');
const {emptyVoice,createVoiceSession}=await server.ssrLoadModule('/src/nativeVoice.ts');
const answer={id:'reply',role:'assistant',status:'complete',content:'<script>sichtbar</script>',created_at:'2026-10-09',metadata:{context:{}}};
function fixture(){const requests=[],drafts=[];let voice;const session=createVoiceSession({post:body=>{requests.push(body);return true;},newId:()=>crypto.randomUUID(),active:()=>true,changed:state=>voice.state=state});
voice={state:{...emptyVoice},startDraft:(base,commit)=>session.startDraft(base,commit),finish:()=>session.finish(),cancel:()=>session.cancel(),read:msg=>session.read(msg,async()=>msg,()=>msg)};
session.probe();session.event({id:requests.at(-1).id,state:'ready',text:'',dictationAvailable:true,speechAvailable:true});return {voice,session,requests,drafts};}
const render=(Component,props)=>renderToStaticMarkup(createElement(Component,props));
function buttons(node,result=[]){if(!node||typeof node!=='object')return result;if(node.type==='button')result.push(node);for(const child of [node.props?.children].flat(10))buttons(child,result);return result;}
test('old browser has neither placeholder microphone nor local playback control',()=>{const voice={state:{...emptyVoice}};assert.equal(render(VoiceDraftControls,{voice,disabled:false,base:'existing',onDraft:()=>{}}),'');assert.equal(render(VoiceReply,{voice,message:answer,disabled:false}),'');assert.equal(render(VoiceDraftStatus,{voice}),'');});
test('explicit mic button starts only a draft; ending through real status handler preserves typed text',()=>{const f=fixture();const button=VoiceDraftControls({voice:f.voice,disabled:false,base:'Vorher',onDraft:text=>f.drafts.push(text)});assert.equal(button.props.type,'button');button.props.onClick();const id=f.requests.at(-1).id;assert.equal(f.requests.at(-1).aktion,'spracheStart');f.session.event({id,state:'listening',text:'Zusatz',dictationAvailable:true,speechAvailable:true});assert.deepEqual(f.drafts,[]);const tree=VoiceDraftStatus({voice:f.voice});assert.match(renderToStaticMarkup(tree),/Noch nichts gesendet/);buttons(tree)[0].props.onClick();assert.equal(f.requests.at(-1).aktion,'spracheEnde');f.session.event({id,state:'completed',text:'Zusatz',dictationAvailable:true,speechAvailable:true});assert.deepEqual(f.drafts,['Vorher Zusatz']);assert.match(render(VoiceDraftStatus,{voice:f.voice}),/selbst senden/);});
test('real cancel button discards only spoken addition, never commits or sends',()=>{const f=fixture();VoiceDraftControls({voice:f.voice,disabled:false,base:'behalten',onDraft:text=>f.drafts.push(text)}).props.onClick();buttons(VoiceDraftStatus({voice:f.voice}))[1].props.onClick();assert.equal(f.requests.at(-1).aktion,'spracheAbbrechen');assert.deepEqual(f.drafts,[]);});
test('a busy capture disables another mic and playback; finalization retains an enabled cancel',()=>{const f=fixture();f.voice.state={...f.voice.state,phase:'finishing'};assert.equal(VoiceDraftControls({voice:f.voice,disabled:false,base:'',onDraft:()=>{}}).props.disabled,true);assert.equal(VoiceReply({voice:f.voice,message:answer,disabled:false}).props.disabled,true);const actions=buttons(VoiceDraftStatus({voice:f.voice}));assert.equal(actions[0].props.disabled,true);assert.equal(actions[1].props.disabled,undefined);});
test('reply control performs fresh read only on click and changes to stop during playback',async()=>{const f=fixture();const button=VoiceReply({voice:f.voice,message:answer,disabled:false});assert.equal(f.requests.filter(r=>r.aktion==='spracheVorlesen').length,0);assert.equal(button.props.type,'button');await button.props.onClick();assert.equal(f.requests.at(-1).aktion,'spracheVorlesen');const active=VoiceReply({voice:f.voice,message:answer,disabled:false});assert.match(renderToStaticMarkup(active),/Vorlesen stoppen/);active.props.onClick();assert.equal(f.requests.at(-1).aktion,'spracheStopp');});
test('partial transcript is escaped and error/user messages have no playback action',()=>{const f=fixture();f.voice.state={...f.voice.state,phase:'listening',partial:'<script>synthetic</script>'};assert.match(render(VoiceDraftStatus,{voice:f.voice}),/&lt;script&gt;/);assert.equal(render(VoiceReply,{voice:f.voice,message:{...answer,status:'error'},disabled:false}),'');assert.equal(render(VoiceReply,{voice:f.voice,message:{...answer,role:'user'},disabled:false}),'');});
test('refresh for playback uses the existing same-origin GET with a cancel signal, no model endpoint',async()=>{const {api}=await server.ssrLoadModule('/src/api.ts');const old=globalThis.fetch, calls=[];globalThis.fetch=async(path,init)=>{calls.push({path,init});return {ok:true,json:async()=>({conversation:{id:'conversation'},messages:[answer]})};};try{const signal=new AbortController().signal;await api.getConversation('conversation',signal);assert.deepEqual(calls.map(c=>c.path),['/api/v1/conversations/conversation']);assert.equal(calls[0].init.signal,signal);assert.equal(calls[0].init.body,undefined);assert.equal(calls[0].init.method,undefined);}finally{globalThis.fetch=old;}});
